site_name: Rollback Agent System
site_description: AI Agent system with checkpoint rollback capabilities
site_author: Your Name
site_url: https://yourdomain.com

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            separate_signature: true
            line_length: 80

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
  - API Reference:
    - Authentication:
      - User: api/auth/user.md
      - User Repository: api/database/user_repository.md
    - Database:
      - Repositories: api/database/repositories.md
    - Sessions: api/sessions.md
    - Checkpoints: api/checkpoints.md
    - Agents: api/agents.md
  - Architecture:
    - Overview: architecture/overview.md
    - Database Schema: architecture/database.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/rollback-agent